@startuml
class System
{
    - GenericWindow windows[]
    - GenericWindow* currentWindow
    - Canvas c
    + draw() // loop over windows and next calls c.render()
    + keyboard_handler()
}


abstract GenericWindow
{
    + {abstract} draw(Canvas &c, int x, int y)
}

class Canvas
{
    + render()
    + string[H] canvas
}

System *-- Canvas
System *-- GenericWindow


class PopupWindow
class Frame
class ListWindow
{
    - Item items[]
    - Item* current_item
    + {abstract} navigate()
}
Frame <|-- ListWindow
Frame <|-- PopupWindow
GenericWindow <|-- Frame

abstract Item
{
    - String name
    - float price
    - float price_min
    - float price_max
    + getPrice()
    + getName()
    + setPriceRange()
    + updatePrice()
}
class Stock
{
    - int quantity
    + getQty()
    + setQty()
    + buy(int n)
    + sell(int n)
}
class Ticket
{
    
}
Item <|-- Stock
Item <|-- Ticket

ListWindow *- Item
@enduml
