name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run cmake
      run: cmake CMakeLists.txt
    - name: run make
      run: make
    - name: make dir for test files
      run: mkdir ../test
    - name: copy test files 
      run: cp test/*.txt ../test/
    - name: run tests
      run: ./runTests
      
      
