name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: create build directory
      run: mkdir build && cd build
    - name: run cmake
      run: cmake ..
    - name: run make
      run: make
    - name: run tests
      run: ./runTests
      
      
